/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPerson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllEmployees"];
        put?: never;
        post: operations["createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-inventories/top3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTop3ProductInventories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEmployeeById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-inventories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteProductInventory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Businessentity: {
            /** Format: int32 */
            id?: number;
            /** Format: uuid */
            rowguid?: string;
            /** Format: date-time */
            modifieddate?: string;
        };
        Person: {
            /** Format: int32 */
            id?: number;
            businessentity?: components["schemas"]["Businessentity"];
            persontype: string;
            namestyle?: boolean;
            title?: string;
            firstname?: string;
            middlename?: string;
            lastname?: string;
            suffix?: string;
            /** Format: int32 */
            emailpromotion: number;
            additionalcontactinfo?: {
                [key: string]: string;
            };
            demographics?: {
                [key: string]: number;
            };
            /** Format: uuid */
            rowguid?: string;
            /** Format: date-time */
            modifieddate?: string;
        };
        Employee: {
            /** Format: int32 */
            id?: number;
            nationalidnumber: string;
            loginid: string;
            jobtitle: string;
            /** Format: date */
            birthdate: string;
            maritalstatus: string;
            gender: string;
            /** Format: date */
            hiredate: string;
            salariedflag?: boolean;
            /** Format: int32 */
            vacationhours: number;
            /** Format: int32 */
            sickleavehours: number;
            currentflag?: boolean;
            /** Format: uuid */
            rowguid: string;
            /** Format: date-time */
            modifieddate: string;
            organizationnode?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        Product: {
            /** Format: int32 */
            productId?: number;
            productNumber?: string;
            name?: string;
        };
        ProductInventory: {
            /** Format: int32 */
            locationId?: number;
            product?: components["schemas"]["Product"];
            /** Format: int32 */
            quantity?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createPerson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Person"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Person"];
                };
            };
        };
    };
    getAllEmployees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Employee"][];
                };
            };
        };
    };
    createEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Employee"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Employee"];
                };
            };
        };
    };
    getTop3ProductInventories: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductInventory"][];
                };
            };
        };
    };
    getEmployeeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Employee"];
                };
            };
        };
    };
    deleteProductInventory: {
        parameters: {
            query: {
                productId: number;
                locationId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
