services:
  database:
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - adventure_works_postgres_db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  init-db:
    image: postgres:18
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./src/infra/init_database.sh:/init_database.sh:ro
    entrypoint: ["/bin/sh", "/init_database.sh"]
    restart: "no"

#  backend:
#    image: experimentalsoftware/spring-adventures:backend-latest
#    ports:
#      - "8000:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/Adventureworks

volumes:
  adventure_works_postgres_db:
